### PR TITLE
Updated SERP README.md

### PR DESCRIPTION
**Pull request by Phoenix2809**
Provided Instructions for serper.dev API key creation and configuring it in the Toolkit Page

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update

### Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have read the contributing guide and my code conforms to the guidelines.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have added the required tests.

### CODE REVIEW

**Review by clappo143 — COMMENTED** [review]
This looks good (note that your account username appears in the new screenshot). 

It might also be worth updating `config_template.yaml`, specifying that the API key for the SERP Search tool needs to be from https://serper.dev/ (there are multiple providers). Also, the way the comments/instructions read is a bit confusing – it suggests that users should either provide a key for Google-API/CSE or alternatively for SERP, but not both. The serper.dev key is arguably easier to obtain, but also, there is no reason why users cannot provide keys for both (and create agents with access to both tools). 

Not sure if that makes sense, but here are the lines I'm referring to: 

```
#If you have google api key and CSE key, use this
GOOGLE_API_KEY: YOUR_GOOGLE_API_KEY
SEARCH_ENGINE_ID: YOUR_SEARCH_ENIGNE_ID

# IF YOU DONT HAVE GOOGLE SEARCH KEY, USE THIS
SERP_API_KEY: YOUR_SERP_API_KEY
```

**Review by clappo143 — APPROVED** [review]
Nice one

**Comment by Phoenix2809** [comment]
@clappo143 Thanks for pointing it out. I have made the necessary changes in the Config_Template.yaml and the image as well.

**Review by neelayan7 — APPROVED** [review]
Looks good.

**Pull request merged**
