### PR TITLE
Added local llm functionality by incorporating text-generation-webui

### PR DESCRIPTION
**Pull request by sirajperson**
In this PM I have integrated text-generation-webui as a means of managing locally hosted LLMs. 
In this PM the changes are as follows:
Created a setting for OPENAI_API_BASE_URL: This allows one to set the URL that the openai library is pointed to.
Created a docker image of Text Generation Web UI that includes multi-GPU off loading of GGMLs
Configured SuperAGI to use use the TGWUI docker image by default. 

With this PM one can run the docker-compose up --build command, and then navigate to localhost:7860 to download models for use with SuperAGI from huggingface.co.

### CODE REVIEW

**Review by Renegadesoffun — APPROVED** [review]

**Comment by Renegadesoffun** [comment]
Im all about this!! I think we all wanted autogpt to run locally to push the limits without the bank! Stoked to see what we can run locally. And yeah then optimization of gpu preset, cblast, llama etc. will be next to auto optimize locall llms. Great job tho! 👏

**Comment by TransformerOptimus** [comment]
Tried running docker-compose on new changes(on macbook 16gb RAM). Getting the following error.

#0 32.90 Ignoring bitsandbytes: markers 'platform_system == "Windows"' don't match your environment
#0 32.90 Ignoring llama-cpp-python: markers 'platform_system == "Windows"' don't match your environment
#0 32.90 Ignoring auto-gptq: markers 'platform_system == "Windows"' don't match your environment
#0 32.90 ERROR: auto_gptq-0.2.0+cu117-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.
------
failed to solve: executor failed running [/bin/sh -c pip3 install -r /app/requirements.txt]: exit code: 1

**Comment by sirajperson** [comment]
> @sirajperson. This is awesome.
> 
> Tried running docker-compose on new changes(on macbook 16gb RAM). Getting the following error.
> 
> ## 0 32.90 Ignoring bitsandbytes: markers 'platform_system == "Windows"' don't match your environment
> 0 32.90 Ignoring llama-cpp-python: markers 'platform_system == "Windows"' don't match your environment
> 0 32.90 Ignoring auto-gptq: markers 'platform_system == "Windows"' don't match your environment
> 0 32.90 ERROR: auto_gptq-0.2.0+cu117-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.
> failed to solve: executor failed running [/bin/sh -c pip3 install -r /app/requirements.txt]: exit code: 1

Thanks for the reply. As for the build, are you able to build the docker image on the main branch?

**Comment by sirajperson** [comment]
Okay, it looks like there error that you are getting is while trying to execute the install requirements.txt file from text generation web ui. On line 25 of tgwui_requirements.txt try commenting out the last line. In order to make this work on your local machine there are a couple of installation steps that you may have to take using mac. I'm not sure what kind of video card you have, or if you are using a laptop, but you should be able to remove that last line from the requirements.txt file to get it installed. 

Also, I have removed the following items from the launch arguments so that TGWUI doesn't automatically target devices with nvidia GPUs. 
 
For now configuration of the docker-compose.yaml needs to be done manually. I will create an build.sh script tonight that will create the docker-compose.yaml file to load build options based on the target installation environment.

**Comment by sirajperson** [comment]
@TransformerOptimus 
Another hiccup I've run into in working with LLMs is the difference in token length between llama's, and it's derivatives', token limit. The token limit of lama is 2048 while the token limit for gpt-3.5 and gpt-4 are 4096 and 8192 (for the api version) respectively. I was thinking that it might be a good idea to consider token limits in the session formation. I will work on a sample something like that later tonight, but any ideas would be greatly appreciated.

**Comment by TransformerOptimus** [comment]
> @TransformerOptimus
> Another hiccup I've run into in working with local LLMs is the difference in token length between llama's, and it's derivatives', token limit. The token limit of lama is 2048 while the token limit for gpt-3.5 and gpt-4 are 4096 and 8192 (for the api version) respectively. I was thinking that it might be a good idea to consider token limits in the session formation. I'll will work on a something like that later tonight, but any ideas would be greatly appreciated.

There are multiple components in a prompt. 
1. Base prompt - includes goals, constraints, tools etc.
2. Short term memory
3. Long term memory(WIP)
4. Knowledge base - preseeded knowledge for agents (it is WIP). 

We can give certain percentage of weight to each of components. 
Base prompt weight can’t be changed but we can come up with variations. STM, LTM, Knowledge can have a weight of 1/3 of remaining tokens available or can be kept configurable.

**Comment by luciferlinx101** [comment]
@sirajperson Hey can you let me know what to do after localhost:7860 I was able to set up locally but how to choose and test with different model?
can you explain in detail what are the next steps after ```docker compose up --build```

**Comment by TransformerOptimus** [comment]
Can we keep the new docker-compose with local llm different from the current docker-compose file (something like - docker-compose.local_llm.yaml). We don't know how many devs want to run the local model directly by default. We can add a section in the readme for the local model.

**Comment by sirajperson** [comment]
@TransformerOptimus Sure, It would be nice to be able to specify the use of local LLMs as a build arg. If we hand docker-compose something like --build-args use_local_llm=true than the compose executes the tgwui build.

**Comment by sirajperson** [comment]
In my last commit  everything seems to be basically working. I've had 4 successful runs in the past 24 hours. I'll go ahead and separate the docker-compose files. Let me know if the last commit is working well on Mac. I'm on Linux.

**Comment by sirajperson** [comment]
@luciferlinx101 As of the last commit, Jun 10, to use Local LLMs follow these steps:
Clone my development branch
Copy the config_template.yaml to config.yaml

Edit the config.yaml file and make the following changes:
Comment out line 7:  OPENAI_API_BASE: https://api.openai.com/v1
Uncomment line 8: #OPENAI_API_BASE: "http://super__tgwui:5001/v1"

Modify the following lines to match the model you plan on using:
MAX_TOOL_TOKEN_LIMIT: 800
MAX_MODEL_TOKEN_LIMIT: 4032 # set to 2048 for llama

For llama based models I have successfully been using 500, and 2048 respectively

Run docker compose:
docker-compose up --build

Note, that if you want to use more advanced features like loading models into GPUs then you will need to do additional configuration in the docker-compose.yaml file. I have tried to leave comments in the current file as basic instructions. For more information on specific text-generation-webui builds I would recommend that you review the instructions on the text-generation-webui-docker github repo. https://github.com/Atinoda/text-generation-webui-docker

Please be aware that my fork is development branch and is undergoing a PR, and will be changing more soon. In other words, it isn't stable.

**Comment by TransformerOptimus** [comment]
> In my last commit everything seems to be basically working. I've had 4 successful runs in the past 24 hours. I'll go ahead and separate the docker-compose files. Let me know if the last commit is working well on Mac. I'm on Linux.

Mac it is still failing. Getting this error. Seems running fine on ubuntu.
#0 17.80   
#0 17.80   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 17.80   ERROR: Failed building wheel for llama-cpp-python
#0 17.80 Failed to build llama-cpp-python
#0 17.80 ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
------
failed to solve: executor failed running [/bin/sh -c pip uninstall -y llama-cpp-python &&     CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python]: exit code: 1

**Comment by TransformerOptimus** [comment]
> > In my last commit everything seems to be basically working. I've had 4 successful runs in the past 24 hours. I'll go ahead and separate the docker-compose files. Let me know if the last commit is working well on Mac. I'm on Linux.
> 
> ## Mac it is still failing. Getting this error. Seems running fine on ubuntu.
> #0 17.80
> #0 17.80 note: This error originates from a subprocess, and is likely not a problem with pip.
> #0 17.80 ERROR: Failed building wheel for llama-cpp-python
> #0 17.80 Failed to build llama-cpp-python
> #0 17.80 ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
> failed to solve: executor failed running [/bin/sh -c pip uninstall -y llama-cpp-python && CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python]: exit code: 1

Ran the code change on https://lmsys.org/about/ and was able to get 

> @TransformerOptimus Sure, It would be nice to be able to specify the use of local LLMs as a build arg. If we hand docker-compose something like --build-args use_local_llm=true than the compose executes the tgwui build.

Sounds good

**Comment by sirajperson** [comment]
@TransformerOptimus I'm modifying the default build to remove llama-cuda.

**Comment by sirajperson** [comment]
Okay I'll do a fresh clone and see if it works. I might just pull the macbook off the shelf and spin it up to debug. Although my mac is an x68 from '18. I'm not sure if I can reproduce. Let me know if commenting out the build line resolved the build issue.

**Comment by luciferlinx101** [comment]
@sirajperson 
Getting error:
failed to solve: failed to compute cache key: failed to calculate checksum of ref moby::ofh3vz56pr1wh8d19h9bzjm6o: "/tgwui/scripts/docker-entrypoint.sh": not found

**Comment by TransformerOptimus** [comment]
> Okay I'll do a fresh clone and see if it works. I might just pull the macbook off the shelf and spin it up to debug. Although my mac is an x68 from '18. I'm not sure if I can reproduce. Let me know if commenting out the build line resolved the build issue.

commenting out build line resolved the earlier error(auto_gptq-0.2.0+cu117-cp310-cp310-linux_x86_64.whl issue) . New error related to llama-cpp-python.

**Comment by luciferlinx101** [comment]
> @sirajperson Getting error: failed to solve: failed to compute cache key: failed to calculate checksum of ref moby::ofh3vz56pr1wh8d19h9bzjm6o: "/tgwui/scripts/docker-entrypoint.sh": not found

Cloning new repo somehow resolved it.

**Comment by sirajperson** [comment]
@luciferlinx101 Sorry about that, In the process of doing commits.

**Comment by luciferlinx101** [comment]
@sirajperson 
Got error: 
Traceback (most recent call last): File “/app/server.py”, line 180, in download_model_wrapper model, branch = downloader.sanitize_model_and_branch_names(model, branch) File “/app/download-model.py”, line 82, in sanitize_model_and_branch_names if model[-1] == ‘/’: IndexError: string index out of range

I was able to open http://localhost:7860/
and added TheBloke/Vicuna-13B-CoT-GGML in the  LoRAS(s) field and kept all other fields same as it was.

Sharing a screen shot.

image

Let me know if I am doing anything wrong.

**Comment by sirajperson** [comment]
@luciferlinx101 From the picture it looks like you have the huggingface identifier in the wrong text field. Please try cutting the text from the 'LoRA(s)' field and pasting it into the 'Download custom models or LoRA' field at the bottom of the UI.

**Comment by sirajperson** [comment]
@TransformerOptimus 
Okay, I was able to merge the recent commits from the main branch. I was able to launch and run on GPU mode, CPU mode (with distributed GGML offloading). Please let me know if you're running smooth on Mac. Also, give me a list of tasks you'd like to complete for merging with main. Thanks :-D

**Comment by sirajperson** [comment]
@luciferlinx101 If you don't mind could you please rebuild the PR in your testing environment and let me know if everything is working correctly?

**Comment by sirajperson** [comment]
@TransformerOptimus 
After looking back through the logs I am finding the following error. I'm looking into it, but I'm not sure if the problem exists in the MB at the moment or not. Any insight is appreciated. 

celery_1           | [2023-06-10 23:38:44,948: ERROR/ForkPoolWorker-7] Task execute_agent[6015bb37-cd89-4f4f-9d75-b96ae0e4bffe] raised unexpected: DataError("Invalid input of type: 'list'. Convert to a bytes, string, int or float first.")
celery_1           | Traceback (most recent call last):
celery_1           |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
celery_1           |     R = retval = fun(*args, **kwargs)
celery_1           |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
celery_1           |     return self.run(*args, **kwargs)
celery_1           |   File "/usr/local/lib/python3.9/site-packages/celery/app/autoretry.py", line 54, in run
celery_1           |     ret = task.retry(exc=exc, **retry_kwargs)
celery_1           |   File "/usr/local/lib/python3.9/site-packages/celery/app/task.py", line 717, in retry
celery_1           |     raise_with_context(exc)
celery_1           |   File "/usr/local/lib/python3.9/site-packages/celery/app/autoretry.py", line 34, in run
celery_1           |     return task._orig_run(*args, **kwargs)
celery_1           |   File "/app/superagi/worker.py", line 18, in execute_agent
celery_1           |     AgentExecutor().execute_next_action(agent_execution_id=agent_execution_id)
celery_1           |   File "/app/superagi/jobs/agent_executor.py", line 149, in execute_next_action
celery_1           |     response = spawned_agent.execute(agent_template_step)
celery_1           |   File "/app/superagi/agent/super_agi.py", line 184, in execute
celery_1           |     task_queue.add_task(task)
celery_1           |   File "/app/superagi/agent/task_queue.py", line 16, in add_task
celery_1           |     self.db.lpush(self.queue_name, task)
celery_1           |   File "/usr/local/lib/python3.9/site-packages/redis/commands/core.py", line 2706, in lpush
celery_1           |     return self.execute_command("LPUSH", name, *values)
celery_1           |   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1269, in execute_command
celery_1           |     return conn.retry.call_with_retry(
celery_1           |   File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
celery_1           |     return do()
celery_1           |   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1270, in <lambda>
celery_1           |     lambda: self._send_command_parse_response(
celery_1           |   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1245, in _send_command_parse_response
celery_1           |     conn.send_command(*args)
celery_1           |   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 848, in send_command
celery_1           |     self._command_packer.pack(*args),
celery_1           |   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 558, in pack
celery_1           |     for arg in map(self.encode, args):
celery_1           |   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 115, in encode
celery_1           |     raise DataError(
celery_1           | redis.exceptions.DataError: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.

**Comment by sirajperson** [comment]
@TransformerOptimus 
With GPU mode I'm getting 0.04ms per token with a 13B CoT fully offloaded to GPU model. I'd call that pretty usable! :_D

**Comment by luciferlinx101** [comment]
@sirajperson I was able to downlaod and set that model using http://localhost:7860/ and selected TheBloke/Vicuna-13B-CoT-GGML

Now  howshould I use it?
going to localhost:3000 doesn't seem working 
I removed my Open AI key and wanted to test this model
Agent gets stuck in thinking but the model downloaded doesnt seems to be used.Anything wrong at my end?

**Comment by TransformerOptimus** [comment]
> --build-args
Gettting "text-generation-webui       | OSError: cannot load library 'libsndfile.so': libsndfile.so: cannot open shared object file: No such file or directory" in mac

Let's separate the docker-compose files and update readme on running local llm we are good to go for main.

**Comment by sirajperson** [comment]
@TransformerOptimus 
In the last commit I'v separated the docker compose files such with the following build schema:

Default build, no local LLMs or OPENAI_API_BASE redirect.
docker-compose up --build

Build with local GPU LLM support. This mode uses memory caching by default. It isn't very fast, but it works on a much greater number of host machines than using GPU mode. 
docker-compose -f local-llm up --build

And finally, the more advanced GPU build. This build may require that additional packages be installed on the host machine. I would suggest that anyone trying to build a GPU install of the container read the docs on the in the Text Generation Web UI doc files. They very informative well written. [TGWUI Docs](https://github.com/oobabooga/text-generation-webui/tree/main/docs)
docker-compose -f local-llm-gpu up --build

Please note, that Text Generation Web UI is a large project with lots of functionality. It's worth taking time to get to know it to use local LLMs efficiently

**Comment by sirajperson** [comment]
@luciferlinx101 I quite a bit of time looking for the that was causing a hang with the agent execution. Please look over the README.md file in the openai plugin root folder of TGWUI. The openai plugin is currently under development and is not yet fully implemented. This PR is for integration of TGWUI as a model management tool. The issue might be easier solved by creating an issue on the projects issue tracker as not being able to sequence API calls to the OpenAI api plugin. The readme can found [here](https://github.com/oobabooga/text-generation-webui/blob/main/extensions/openai/README.md).

**Comment by luciferlinx101** [comment]
@sirajperson Sure I will test and let you know if it works properly.

**Comment by TransformerOptimus** [comment]
Merging it to dev. We will merge the dev -> main along with other changes tomorrow. I could able to get it running in Windows and Ubuntu VM.
Able to get it running on my windows. 
Mac still throwing "ERROR: auto_gptq-0.2.2+cu117-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform" error again.

**Comment by luciferlinx101** [comment]
@sirajperson I was also able to get the tool http://localhost:7860/ and download the model but we wanted proper readme after this step which could be used to use this local model as part of super agi such that in frontend people seeing the agent actually runs on this local model not open ai.

This will help all users once we merge dev to main.

**Comment by sirajperson** [comment]
Sure, I'll be happy to do that.

**Comment by sirajperson** [comment]
@TransformerOptimus 

I'll go ahead and get to the bottom of that bug. Commenting out the line changes the Dockerfile that is present on the TGWUI docker github project. I would like to avoid changing files, and to try to keep it the same. That way instead of having additional folders, files, and configurations down the line we can just do a git pull for the repo, so long as it's maintained. For now, I will go ahead and comment it out until the issue is investigated further.

**Comment by atxcowboy** [comment]
> @TransformerOptimus In the last commit I'v separated the docker compose files such with the following build schema:
> 
> Default build, no local LLMs or OPENAI_API_BASE redirect. docker-compose up --build
> 
> Build with local GPU LLM support. This mode uses memory caching by default. It isn't very fast, but it works on a much greater number of host machines than using GPU mode. docker-compose -f local-llm up --build
> 
> And finally, the more advanced GPU build. This build may require that additional packages be installed on the host machine. I would suggest that anyone trying to build a GPU install of the container read the docs on the in the Text Generation Web UI doc files. They are very informative and well written. [TGWUI Docs](https://github.com/oobabooga/text-generation-webui/tree/main/docs) docker-compose -f local-llm-gpu up --build
> 
> Please note, that Text Generation Web UI is a large project with lots of functionality. It's worth taking time to get to know it to use local LLMs efficiently

This is great! I am familiar with Oobabooga and developed a little extension for it. 

A few observations:

- I got it to spin up with GPU support and the model loads about 10 times faster with GPU support rather than CPU on my system. I would clearly prefer to be able to just point to my own customized defined Ooobabooga installation location at a certain URL as I'd want to make use of gptq and other extended capabilities. I guess ideally a user gets the choice between using the dockerized version or a custom endpoint.

- On the GPU I also get the error you mentioned:
`redis.exceptions.DataError: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.`

- On the Create Agent Screen SuperAGI would need to be aware of the available LLMs, as it currently only shows the predefined ChatGPT models.
createagent

**Comment by luciferlinx101** [comment]
> @luciferlinx101 Sure, I'll be happy to do that.

Hey any updates of the stepwise readme showing end to end use case with superagi?

**Comment by sirajperson** [comment]
@luciferlinx101 
Sorry, about the delay. Been a bit busy this week. LoL

**Comment by GuruVirus** [comment]
Adding encouragement for @sirajperson : more of us are watching for the steps to successfully set this up.

**Comment by luciferlinx101** [comment]
> @luciferlinx101 Sorry, about the delay. Been a bit busy this week. LoL

No problem! Let me know if is done.

**Comment by malicorX** [comment]
i'm running this for ooba:

malicor@DESKTOP-I087DO5:/mnt/d/ai/oobabooga_WSL/text-generation-webui$ python3 server.py --wbits 4 --groupsize 128 --model_type llama --model WizardLM-7B-uncensored-GPTQ --api --extensions long_term_memory, EdgeGPT --no-stream

i can use ooba via http://localhost:7860/ and if i ask it "how many legs does a spider have", it gives me correct answer

i started superAGI with:

D:\AI\SuperAGI>docker-compose -f local-llm-gpu up --build

it did a lot of installing and ended up with:

superagi-gui-1              | - ready started server on 0.0.0.0:3000, url: http://localhost:3000
superagi-gui-1              | - event compiled client and server successfully in 957 ms (1314 modules)
superagi-gui-1              | - wait compiling...
superagi-gui-1              | - event compiled client and server successfully in 218 ms (1314 modules)
superagi-super__postgres-1  | 2023-06-17 08:26:33.196 UTC [26] LOG:  checkpoint starting: time
superagi-super__postgres-1  | 2023-06-17 08:26:33.230 UTC [26] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.008 s, sync=0.004 s, total=0.035 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB
superagi-gui-1              | - wait compiling /_error (client and server)...
superagi-gui-1              | - event compiled client and server successfully in 135 ms (1315 modules)
superagi-gui-1              | Do not add stylesheets using next/head (see <link rel="stylesheet"> tag with href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap"). Use Document instead.
superagi-gui-1              | See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component
superagi-gui-1              | Do not add stylesheets using next/head (see <link rel="stylesheet"> tag with href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"). Use Document instead.
superagi-gui-1              | See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component
superagi-gui-1              | - wait compiling /favicon.ico/route (client and server)...
superagi-gui-1              | - event compiled successfully in 43 ms (146 modules)

in the config.yaml file i set this:

# For locally hosted LLMs comment out the next line and uncomment the one after
# to configure a local llm point your browser to 127.0.0.1:7860 and click on the model tab in text generation web ui.
#OPENAI_API_BASE: https://api.openai.com/v1
OPENAI_API_BASE: "http://super__tgwui:5001/v1"

# "gpt-3.5-turbo-0301": 4032, "gpt-4-0314": 8092, "gpt-3.5-turbo": 4032, "gpt-4": 8092, "llama":2048, "mpt-7b-storywriter":45000
MODEL_NAME: "gpt-3.5-turbo-0301"
MAX_TOOL_TOKEN_LIMIT: 500 # or 800 for gpt3.5
MAX_MODEL_TOKEN_LIMIT: 2048 # set to 2048 for llama or 4032 for gpt3.5


when i now start http://localhost:3000/ i get the purple superAGI screen and it saying "Initializing superAGI", but it's stuck there.

any idea what i m doing wrong?

**Comment by malicorX** [comment]
i m not sure if i did something wrong, or if my last comment was deleted (i m new to github). would be nice if someone could write a line to explain me briefly

**Comment by kolisn** [comment]
I don't believe tgwui should be "incorporated" into the same docker image. 
If we can include local LLM usage like, by pointing to an external service [https://github.com/TavernAI/TavernAI](TavernAI) that would be amazing. 
Is this already possible or would this be worth working towards?

**Comment by DaKingof** [comment]
It would be fantastic to have a tut that goes over how to set up open source LLM's with SuperAGI. I would love to do test runs on my own hardware to see if my configuration looks pretty good, then take it out to the more powerful LLM's after I have confirmed it looked like I am close to where I need to be with my instructions.

Also, we could save some work by pointing to the oobabooga installation instructions for their part...but hooking into SuperAGI seems to be the part I am amiss at here.

**Comment by sirajperson** [comment]
> i'm running this for ooba:
> 
> malicor@DESKTOP-I087DO5:/mnt/d/ai/oobabooga_WSL/text-generation-webui$ python3 server.py --wbits 4 --groupsize 128 --model_type llama --model WizardLM-7B-uncensored-GPTQ --api --extensions long_term_memory, EdgeGPT --no-stream
> 
> i can use ooba via http://localhost:7860/ and if i ask it "how many legs does a spider have", it gives me correct answer
> 
> i started superAGI with:
> 
> D:\AI\SuperAGI>docker-compose -f local-llm-gpu up --build
> 
> it did a lot of installing and ended up with:
> 
> superagi-gui-1 | - ready started server on 0.0.0.0:3000, url: http://localhost:3000 superagi-gui-1 | - event compiled client and server successfully in 957 ms (1314 modules) superagi-gui-1 | - wait compiling... superagi-gui-1 | - event compiled client and server successfully in 218 ms (1314 modules) superagi-super__postgres-1 | 2023-06-17 08:26:33.196 UTC [26] LOG: checkpoint starting: time superagi-super__postgres-1 | 2023-06-17 08:26:33.230 UTC [26] LOG: checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.008 s, sync=0.004 s, total=0.035 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB superagi-gui-1 | - wait compiling /_error (client and server)... superagi-gui-1 | - event compiled client and server successfully in 135 ms (1315 modules) superagi-gui-1 | Do not add stylesheets using next/head (see tag with href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap"). Use Document instead. superagi-gui-1 | See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component superagi-gui-1 | Do not add stylesheets using next/head (see tag with href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"). Use Document instead. superagi-gui-1 | See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component superagi-gui-1 | - wait compiling /favicon.ico/route (client and server)... superagi-gui-1 | - event compiled successfully in 43 ms (146 modules)
> 
> in the config.yaml file i set this:
> 
> # For locally hosted LLMs comment out the next line and uncomment the one after
> # to configure a local llm point your browser to 127.0.0.1:7860 and click on the model tab in text generation web ui.
> #OPENAI_API_BASE: https://api.openai.com/v1 OPENAI_API_BASE: "http://super__tgwui:5001/v1"
> 
> # "gpt-3.5-turbo-0301": 4032, "gpt-4-0314": 8092, "gpt-3.5-turbo": 4032, "gpt-4": 8092, "llama":2048, "mpt-7b-storywriter":45000
> MODEL_NAME: "gpt-3.5-turbo-0301" MAX_TOOL_TOKEN_LIMIT: 500 # or 800 for gpt3.5 MAX_MODEL_TOKEN_LIMIT: 2048 # set to 2048 for llama or 4032 for gpt3.5
> 
> when i now start http://localhost:3000/ i get the purple superAGI screen and it saying "Initializing superAGI", but it's stuck there.
> 
> any idea what i m doing wrong?

Yes. The IP that you're using is for the docker image. Since you aren't running docker to use TGUI you are going to need to change the line

OPENAI_API_BASE: "http://super__tgwui:5001/v1"

to

OPENAI_API_BASE URL to http://<your host machines LAN address>:5001/v1

Then you are going to want to either create a port forward from your lan interface controller to your loop back interface, or just run TGWU on your lan interface too. You can do that by setting the run address to 0.0.0.0.

**Comment by DiamondGlassDrill** [comment]
> > i'm running this for ooba:
> > malicor@DESKTOP-I087DO5:/mnt/d/ai/oobabooga_WSL/text-generation-webui$ python3 server.py --wbits 4 --groupsize 128 --model_type llama --model WizardLM-7B-uncensored-GPTQ --api --extensions long_term_memory, EdgeGPT --no-stream
> > i can use ooba via http://localhost:7860/ and if i ask it "how many legs does a spider have", it gives me correct answer
> > i started superAGI with:
> > D:\AI\SuperAGI>docker-compose -f local-llm-gpu up --build
> > it did a lot of installing and ended up with:
> > superagi-gui-1 | - ready started server on 0.0.0.0:3000, url: http://localhost:3000 superagi-gui-1 | - event compiled client and server successfully in 957 ms (1314 modules) superagi-gui-1 | - wait compiling... superagi-gui-1 | - event compiled client and server successfully in 218 ms (1314 modules) superagi-super__postgres-1 | 2023-06-17 08:26:33.196 UTC [26] LOG: checkpoint starting: time superagi-super__postgres-1 | 2023-06-17 08:26:33.230 UTC [26] LOG: checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.008 s, sync=0.004 s, total=0.035 s; sync files=2, longest=0.002 s, average=0.002 s; distance=0 kB, estimate=0 kB superagi-gui-1 | - wait compiling /_error (client and server)... superagi-gui-1 | - event compiled client and server successfully in 135 ms (1315 modules) superagi-gui-1 | Do not add stylesheets using next/head (see tag with href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap"). Use Document instead. superagi-gui-1 | See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component superagi-gui-1 | Do not add stylesheets using next/head (see tag with href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"). Use Document instead. superagi-gui-1 | See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component superagi-gui-1 | - wait compiling /favicon.ico/route (client and server)... superagi-gui-1 | - event compiled successfully in 43 ms (146 modules)
> > in the config.yaml file i set this:
> > # For locally hosted LLMs comment out the next line and uncomment the one after
> > # to configure a local llm point your browser to 127.0.0.1:7860 and click on the model tab in text generation web ui.
> > #OPENAI_API_BASE: https://api.openai.com/v1 OPENAI_API_BASE: "http://super__tgwui:5001/v1"
> > # "gpt-3.5-turbo-0301": 4032, "gpt-4-0314": 8092, "gpt-3.5-turbo": 4032, "gpt-4": 8092, "llama":2048, "mpt-7b-storywriter":45000
> > MODEL_NAME: "gpt-3.5-turbo-0301" MAX_TOOL_TOKEN_LIMIT: 500 # or 800 for gpt3.5 MAX_MODEL_TOKEN_LIMIT: 2048 # set to 2048 for llama or 4032 for gpt3.5
> > when i now start http://localhost:3000/ i get the purple superAGI screen and it saying "Initializing superAGI", but it's stuck there.
> > any idea what i m doing wrong?
> 
> Yes. The IP that you're using is for the docker image. Since you aren't running docker to use TGUI you are going to need to change the line
> 
> OPENAI_API_BASE: "http://super__tgwui:5001/v1"
> 
> to
> 
> OPENAI_API_BASE URL to http://[your host machines LAN address]:5001/v1
> 
> Then you are going to want to either create a port forward from your lan interface controller to your loop back interface, or just run TGWU on your lan interface too. You can do that by setting the run address to 0.0.0.0.

Tried everything it says cannot connect to openAI: OPENAI_API_BASE: "http://localhost:5000/api"  connecting with SillyTavern to the API of oobabooga works, but cannot make it work on SuperAGI, any thoughts? Thanks in advance.

Error I receive: 

superagi-celery-1           | 2023-07-04 15:15:09 UTC - Super AGI - INFO - [/app/superagi/llms/openai.py:79] - Exception:
superagi-celery-1           | [2023-07-04 15:15:09,629: INFO/ForkPoolWorker-8] Exception:
superagi-celery-1           | 2023-07-04 15:15:09 UTC - Super AGI - INFO - [/app/superagi/llms/openai.py:79] - Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97baaac880>: Failed to establish a new connection: [Errno 111] Connection refused'))
superagi-celery-1           | [2023-07-04 15:15:09,629: INFO/ForkPoolWorker-8] Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97baaac880>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by sirajperson** [comment]
@DiamondGlassDrill Port 5000 is the Text Generation Web UI api, which differs from the open AI api endpoints. You will need to enable the openapi extension to work with local LLM models. It can get tricky because not every model is compatible with instruct. You would also need to set up the correct template for prompting. 

python server.py --listen --listen-host 0.0.0.0 --verbose --extensions openai 

There a wide array of configurable settings for local LLMs. To manage the model you can navigate to localhost:7860 and click on the models tab.

**Comment by neelayan7** [comment]
@sirajperson A lot of people have been asking for a guide on how to use SuperAGI with local llms. Can you please help us out with a Readme.md? I think @luciferlinx101 also mentioned this a few weeks back.

**Comment by juangea** [comment]
I tried to make this work, at least to be able to access to the minimum UI, but it seems to not work, I used the main SuperAGI branch and I run it with
`docker-compose -f local-llm-gpu up --build`
But the docker related to Oobabooga never runs, it complains about it being unable to create a volume or something similar.

I want to try with nous-heroes 13B GPTQ superhot with exclama_hf, I had good experience trying it directly in Oobabooga's UI

**Comment by IsleOf** [comment]
How about adding petals support to take load off from local resources?

**Comment by NikolaT0mic** [comment]
Is there any progress on adding support for locally running instances of tgwui? Would love to use the version i already have installed instead of using the dockerized version.

**Pull request merged**
