### PR TITLE
Rabbitmq (close #610)

### PR DESCRIPTION
**Pull request by zhound420**
### Description

A  toolkit that utilizes RabbitMQ as a message broker between GPT agents

### Related Issues

#610 

### Solution and Design

This pull request introduces a new toolkit for SuperAGI: the RabbitMQ Toolkit. This toolkit allows SuperAGI to interact with RabbitMQ, a popular open-source message broker. The toolkit is designed to be used by AI agents for inter-agent communication, enabling more complex and collaborative behaviors.

### Test Plan

Testing is to come once we can get the toolkit enabled, currently the toolkit does not seem to be registering to the app, some fine tuning and changes are to be expected once testing begins. Documentation to come during this process. 

### Type of change

- [ ] New feature (non-breaking change which adds functionality)

### Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have read the contributing guide and my code conforms to the guidelines.

### CODE REVIEW

**Comment by zhound420** [comment]
Hi there, I wanted to mention that if you guys think this is a good idea and want to make it part of the base toolkit, you could add rabbitmq container to the docker stack. We can continue to work on the design of the communication flow once the toolkit is enabled. Would love to hear your thoughts. Thanks.

**Comment by luciferlinx101** [comment]
@zhound420 Hey can you point out the exact use cases of this tool? 
How will it help in agent-to-agent execution?

**Comment by zhound420** [comment]
> Hey can you point out the exact use cases of this tool?
> How will it help in agent-to-agent communication?

I did write a readme.md for the toolkit, here's the portion from it:

Collaborative Problem Solving: Multiple AI agents can work together, leveraging their specialized knowledge or capabilities to solve complex problems.
Multi LLM collaboration: Agents could be from a combination of OpenAI and open-source large language models.

(https://github.com/zhound420/rabbitmq)

For me I want specialized agents to collaborate on a shared goal.

**Comment by zhound420** [comment]
Conflicts resolved in requirements.txt. The toolkit now has its own requirements.txt

**Comment by zhound420** [comment]
Okay, fresh install of the v0.7 branch. Imported in the toolkit from my github url using the gui. I see the tools.json is updated. The greetings tool also shows up. But rabbitmq toolkit is still a now show in the UI. No errors in logs.

`superagi-backend-1          | INFO:     Waiting for application startup.
superagi-backend-1          | 2023-07-05 19:06:09 UTC - Super AGI - INFO - [/app/main.py:147] - Running Startup tasks
superagi-backend-1          | 2023-07-05 19:06:09 UTC - Super AGI - INFO - [/app/main.py:151] - User(id=1, name='SuperAGI User', email='super6@agi.com', password='pass@123',organisation_id=1)
superagi-backend-1          | 2023-07-05 19:06:09 UTC - Super AGI - INFO - [/app/main.py:154] - Organisation(id=1, name='Default Organization - 1')
superagi-backend-1          | 2023-07-05 19:06:18 UTC - Super AGI - INFO - [/app/superagi/helper/tool_helper.py:248] - Toolkits Registered Successfully for Organisation ID : 1!
superagi-backend-1          | 2023-07-05 19:06:20 UTC - Super AGI - INFO - [/app/superagi/helper/tool_helper.py:248] - Toolkits Registered Successfully for Organisation ID : 1!
superagi-backend-1          | 2023-07-05 19:06:20 UTC - Super AGI - INFO - [/app/main.py:268] - Successfully registered local toolkits for all Organisations!
superagi-backend-1          | INFO:     Application startup complete.`

**Pull request closed without merging**
