### PR TITLE
help

### PR DESCRIPTION
**Pull request by DMTarmey**
### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update

### Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have read the contributing guide and my code conforms to the guidelines.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have added the required tests.

### CODE REVIEW

**Review by DMTarmey — COMMENTED** [review]
help

**Review by DMTarmey — COMMENTED** [review]
Yo

**Review by DMTarmey — COMMENTED** [review]
607 Issue Template

**Review by DMTarmey — COMMENTED** [review]
Help me even more

**Review by DMTarmey — COMMENTED** [review]
hellu

**Review by DMTarmey — COMMENTED** [review]
Hello

**Comment by neelayan7** [comment]
Why are you spamming?

**Pull request closed without merging**
