### PR TITLE
LanceDB Implementation

### PR DESCRIPTION
**Pull request by unkn-wn**
Implemented LanceDB following `pinecone.py` format. LanceDB acts as a local vector database, not requiring any API keys to use. 

Tagging @AyushExel from LanceDB

### CODE REVIEW

**Comment by Tdmain** [comment]
Someone’s been going behind me and adding edits to the docs code, and adding apps and websites for crypto from my accounts because they have some way of getting in my api or secret stuff and branching or merging, take all license copyrights back to original how I brought them to be gone over and coded. I appreciate the help you know who I am this is serious on everyone’s part that’s involved. Through me and through our business stuff or trillions hundreds of trillions have been transferred around off Etherscan and all that

Sent from my iPhone

On Jun 22, 2023, at 1:23 PM, Leon Yee ***@***.***> wrote:

﻿

Implemented LanceDB following pinecone.py format.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/TransformerOptimus/SuperAGI/pull/450

Commit Summary

  *   1d67676<https://github.com/TransformerOptimus/SuperAGI/pull/450/commits/1d67676ef3ddf3653e75f83932407a99b75727a9> untested lance implrementation
  *   109d3a8<https://github.com/TransformerOptimus/SuperAGI/pull/450/commits/109d3a89d02531fe17cf6c94515b60a39e6d91df> Update lancedb.py
  *   fa12dc1<https://github.com/TransformerOptimus/SuperAGI/pull/450/commits/fa12dc1495aea2a176512bf0fbcbd798eb51dbe8> 2nd untested implementation
  *   aa3916e<https://github.com/TransformerOptimus/SuperAGI/pull/450/commits/aa3916e6938f499311b68856483cc6b9b4ac5191> Update lancedb.py
  *   f3601a8<https://github.com/TransformerOptimus/SuperAGI/pull/450/commits/f3601a808261c148b51f6fced5d7cd9b78d00e37> added open_table workaround
  *   536c51e<https://github.com/TransformerOptimus/SuperAGI/pull/450/commits/536c51e30ae81a23983a66925cb5e0dd661e86be> Update requirements.txt
  *   c8967e5<https://github.com/TransformerOptimus/SuperAGI/pull/450/commits/c8967e5fca585da919294d63ea855a6d0291e276> Merge branch 'main' into leon/lancedb_integration
  *   b9140af<https://github.com/TransformerOptimus/SuperAGI/pull/450/commits/b9140afdf25c0fa8e10fa494ef1d9c9903043b1d> leon/lancedb_integration

File Changes

(5 files<https://github.com/TransformerOptimus/SuperAGI/pull/450/files>)

  *   M gui/pages/Content/Agents/AgentCreate.js<https://github.com/TransformerOptimus/SuperAGI/pull/450/files#diff-abd685c27181fb5808250db5d2c3da86c27b4f1b7c506d1d1f5c3ec726b24d73> (6)
  *   M requirements.txt<https://github.com/TransformerOptimus/SuperAGI/pull/450/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552> (1)
  *   M superagi/jobs/agent_executor.py<https://github.com/TransformerOptimus/SuperAGI/pull/450/files#diff-97fe632b407d9eda4b7c8c3182d2b5fe86e07c6d87f52e26794be747ae1aa36d> (7)
  *   A superagi/vector_store/lancedb.py<https://github.com/TransformerOptimus/SuperAGI/pull/450/files#diff-0d62f63b60863d0c09f99d8cdd043ffbe6d7a02af931d71b5df9c1d69ce0bee6> (119)
  *   M superagi/vector_store/vector_factory.py<https://github.com/TransformerOptimus/SuperAGI/pull/450/files#diff-18f25a0395bbef6b26346e52d2041f21ea3cbb80d1092e2c2b70ad3e683a8fc6> (16)

Patch Links:

  *   https://github.com/TransformerOptimus/SuperAGI/pull/450.patch
  *   https://github.com/TransformerOptimus/SuperAGI/pull/450.diff

**Comment by AyushExel** [comment]
https://github.com/TransformerOptimus/SuperAGI/issues/288
Hey @TransformerOptimus  @luciferlinx101, Leon Yee from lancedb team took a stab at implementing this integration but we're not sure how we can go about testing it. Can you guys please take a look at it or point us in the right direction? Thanks!

**Comment by luciferlinx101** [comment]
@unkn-wn @AyushExel Hey your changes looks good, can you also add unit test for the same, further we will test and merge with upcoming LTM features which is going live mid of this week.

**Comment by unkn-wn** [comment]
@luciferlinx101 added a unit test file! I was mostly following weaviate's tests, but if there's anything else that should be added, please let me know!

**Comment by AyushExel** [comment]
@luciferlinx101 @TransformerOptimus hey guys! just bumping this is up. Let us know if there's anything needed from our side.

**Comment by TransformerOptimus** [comment]
Merged the changes to dev. We are releasing new version of superagi today with these changes.

**Comment by neelayan7** [comment]
https://github.com/TransformerOptimus/SuperAGI/commit/5c45e27437e2455577c27f5c16c490fc6ded0f5f

We have reverted the changes because of a build issue.
```
#0 19.30 ERROR: Ignored the following versions that require a different python version: 1.9.5 Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, <3.7
#0 19.30 ERROR: Could not find a version that satisfies the requirement pylance>=0.4.20 (from lancedb) (from versions: 0.0.2)
#0 19.30 ERROR: No matching distribution found for pylance>=0.4.20
```

Please look into it.

**Comment by unkn-wn** [comment]
Hi @neelayan7 , Can I know what python version you are using? That error seems like a problem with the `pylance` package being unable to install because of an incompatible python version.

**Comment by luciferlinx101** [comment]
```python 3.9``` is being used.

**Comment by unkn-wn** [comment]
@luciferlinx101 @neelayan7 , could you tell us what architecture and OS you are running on, as well as the entire console logs if you still have it? It may fail to install/build if you are using arm64 linux, but please let us know so we can provide a fix for this.

**Comment by AyushExel** [comment]
@luciferlinx101 Can you please provide these details:
* The OS and arch that you're building on
* Whether or not you're using the containerised setup

**Comment by luciferlinx101** [comment]
Yes, we are using docker you can checkout dockerfiles and docker compose.yaml for all other enviornment related related details.

**Comment by unkn-wn** [comment]
@luciferlinx101 We took a look at the Docker files and tried building it again ourselves, but we're unable to reproduce the error. All packages were installed in the docker container. Could you please let us know exactly how to reproduce it?

**Comment by unkn-wn** [comment]
@luciferlinx101 sorry for the pings, but we found and reproduced the error. The issue is that Lance doesn't support arm64 Linux wheels; could you confirm that this is what you are using as well? If so, is it possible for you to build in x86 for the time being? Sorry for the inconvenience!

**Pull request merged**
